version: '3.8'

services:
  smsweb:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - smsdb
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/X9S6dJr1Z7a2
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  smsdb:
    restart: always
    image: postgres
    container_name: smsdb
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    env_file:
      - .env
  redis:
    image: redis

  nginx:
    restart: always
    image: nginx
    ports:
      - "82:82"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - smsweb
      
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - smsdb
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/X9S6dJr1Z7a2
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A smscenter beat -l info

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - smsdb
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/X9S6dJr1Z7a2
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A smscenter worker -l INFO

volumes:
  postgres_data:
