# Generated by Django 5.0.4 on 2024-04-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=500, verbose_name='Public key')),
                ('private_key', models.CharField(max_length=500, verbose_name='Private key')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('username', models.CharField(max_length=500, verbose_name='Username')),
                ('sms_provider_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.smsprovidertitle', verbose_name='SMS provider title')),
                ('api_keys', models.ManyToManyField(to='accounts.apikey', verbose_name='API keys')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
