# Generated by Django 5.0.4 on 2024-04-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_apikey_private_key_alter_apikey_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='merchant_code',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
