# Generated by Django 5.0.4 on 2024-05-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_merchant_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='api_keys',
        ),
        migrations.RemoveField(
            model_name='account',
            name='merchant_code',
        ),
        migrations.AddField(
            model_name='apikey',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apikey', to='accounts.account', verbose_name='Account'),
        ),
    ]
