# Generated by Django 5.0.4 on 2024-04-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_merchant_code'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobisSMSControlid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=120, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=120, null=True)),
                ('is_bulk', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.apikey')),
            ],
        ),
    ]
